spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ecomm_jrtp

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
 port: 8087

# Application Messages Goes Here
payment-service:
  keys:
    razorPayAPIKey: xxxxxxxxxxxxxxxx
    razorPaySecretKey: xxxxxxxxxxxxxx
